# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(help_text='(i.e. Ancient Mediterranean, or Intro to Economic Analysis)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='3-4 letter abbreviation for a subject (i.e. HUM)', max_length=4)),
                ('name', models.CharField(help_text='full name of the subject (i.e. Humanities)', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Subject'),
        ),
    ]
