# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20170522_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutoring_classes',
            field=models.ManyToManyField(help_text='The courses that this student can tutor in.', to='tutor.Course'),
        ),
    ]
