# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_student_tutoring_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
