# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_auto_20170524_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_classes',
            field=models.ManyToManyField(blank=True, help_text='The courses that this student is currently enrolled in.', related_name='students', to='tutor.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_id',
            field=models.CharField(blank=True, help_text='ProfileID for Google People API', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutoring_classes',
            field=models.ManyToManyField(blank=True, help_text='The courses that this student can tutor in.', related_name='tutors', to='tutor.Course'),
        ),
    ]
