# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0005_category_reindex_at'),
        ('tutor', '0015_auto_20170531_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spirit_category.Category'),
        ),
    ]
