# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='spirit_category.Category'),
        ),
    ]
