# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_auto_20170607_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_id',
        ),
    ]
