# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_remove_student_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='drop_in_hrs',
            field=models.CharField(blank=True, help_text='(i.e. Lib 389 MTWThF 19:00-21:00)', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='office_hours',
            field=models.CharField(blank=True, help_text='(i.e. Eliot 314 M 15:00-17:00, WTh 11:00-11:30)', max_length=1000),
        ),
    ]
