# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_remove_student_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_id',
            field=models.CharField(blank=True, help_text='ProfileID for Google People API', max_length=50, null=True),
        ),
    ]
