# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0021_auto_20170703_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='drop_in_hrs',
            field=models.TextField(blank=True, help_text='(i.e. Lib 389 MTWThF 19:00-21:00)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='office_hours',
            field=models.TextField(blank=True, help_text='(i.e. Eliot 314 M 15:00-17:00, WTh 11:00-11:30)'),
        ),
    ]
